### ISSUE TITLE
Roadmap for 0.62

### ISSUE THREAD

**Issue by MoOx** [necolas/react-native-web#1576]
[RN 0.62 recently cames out](https://reactnative.dev/blog/2020/03/26/version-0.62). I didn't find any release issue nor a milestone that might fit so here are a list of things to handle.
I might have forgotten some, I quickly review [RN 0.62 changelog](https://github.com/react-native-community/releases/blob/master/CHANGELOG.md#0620)

- [x] `ref` of an Animated component is now the internal component and deprecated `getNode`
- [ ] Add isReduceMotionEnabled() plus reduceMotionChanged to AccessibilityInfo https://github.com/facebook/react-native/commit/0090ab32c2aeffed76ff58931930fe40a45e6ebc
- [x] new `Appearance` module (with `getColorScheme`) & `useColorScheme` hook
- [x] missing props on Touchables (need to be detailed)
- [x] `AccessibilityInfo.fetch` deprecated
- [x] Add getNativeScrollRef method to FlatList component
- [x] ScrollView `scrollWithoutAnimationTo` removed
- [x] TextInput `onTextInput` removed
- [x] TextInput `inputView` removed
- [x] TextInput `selectionState` removed
- [x] TextInput ref change https://github.com/facebook/react-native/commit/bbc5c35a61cd3af47ccb2dc62430e4b6a4d4e08f
- [x] `ref` on most primitives is now the host component with other methods attached (stop-gap until something like `ReactNative.measure(hostRef)` lands)
- [x] `accessibilityValue` prop
- [x] Remove PropTypes
- [x] Remove accessibilityStates
- [x] Animated `useNativeDriver` is now required.
- [x] TimePickerAndroid removed
- [x] Platform.select now supports native as an option
- [x] Add HostComponent to the public API of React Native

---

BTW @necolas what do you think about having a version number that is more expressive about the version that is supported (= match 0.x, RNW 0.62 would means that it in sync with RN 0.62 API ) ?

**Comment by necolas** [comment]
Don't think I'm going to add LogBox.

What's "missing props on Touchables"?

What's `onSlidingComplete` accessibility events"?

**Comment by MoOx** [comment]
I understand that you can disagree with some choices (I disagree too), but I think it would be nice to stick to RN APIs to avoid to break RNW promise to mimic RN on the web ("React Native for Web").

Even if we decide not to implement some stuff, we should at lease add "placeholder" so the code just don't break on compilation, even if the behaviour is incorrect.

---

Missing props on Touchable => https://github.com/facebook/react-native/commit/8c0c860e38f57e18296f689e47dfb4a54088c260

onSlidingComplete => https://github.com/facebook/react-native/commit/c7aa6dc8270c0eabc913fe6c617c8131e3f4b3c5

**Comment by necolas** [comment]
There are already APIs this library doesn't export.

The slider thing doesn't seem relevant since you don't get that info on the web and there are no sliders in the core afaik. All the accessibility actions stuff is like that too. On web the Touchables already had the accessibility props

**Comment by MoOx** [comment]
> There are already APIs this library doesn't export.

Yeah I know, but some make sense because you just cannot implement them & some are not started yet, but issues are open so...

For Appearance, it would be the only way to implement a proper dark mode & implementation can be very easily done.
LogBox is also a very convenient tool.
Same thing for Modal & Alert, (btw I think Alert could use Modal with a portal?)

I am thinking about a compromise so people can rely on RNW safely without having to adjust their codebase to find user land solution for some modules.

Would you be open to add a method so that we could inject APIs into rnw ?

Something like 

```js
import {inject} from "react-native-web"

inject("Appearance", "react-native-web-appearance")
```

I know it's not ideal but if you are not open to have 1:1 mapping for the APIs, we should think about an easy way to adjust this in user land.

**Comment by necolas** [comment]
You can already do this in user space with bundlers. This is what Expo does

**Comment by necolas** [comment]
@EvanBacon what do you think we should do about `Appearance` for web? Is the expo module API compatible with the one in RN core?

**Comment by javascripter** [comment]
I think it would help a lot of people if there's documentation on how to add unimplemented/unsupported features without forking or patching.

My current setup for a create-react-app app is below. Something like this should work for webpack users too.

@MoOx 

```javascript
// config-overrides.js
const { addWebpackAlias, babelInclude, override } = require('customize-cra')

module.exports = override(
  addWebpackAlias({
     // This file, located at src/react-native-web-compat.js, re-exports react-native-web with some modifications
    'react-native': 'react-native-web-compat'
  }),
  babelInclude([
    path.resolve('src'),
  ])
)
```

```javascript
// src/react-native-web-compat.js
export * from 'react-native-web'
export const ViewPropTypes = {} // 😉
```

**Comment by necolas** [comment]
Importing all the modules like that breaks the babel plugin optimizations. You should use Expo as they have a webpack config for all this. APIs like ViewPropTypes are being removed from RN soon so you need to migrate off those anyway

**Comment by MoOx** [comment]
Weird, I wasn't able to find modal or alert in expo codebase nor expo-cli. There is some alias indeed but wasn't able to find modal or alert implementation or alias anywhere...
I did see the webpack config but nothing here for all missing modules https://github.com/expo/expo-cli/blob/master/packages/webpack-config/src/env/alias.ts

**Comment by jfrolich** [comment]
I think the Expo package for `Appearance` was a bundled prerelease to implement dark mode before it shipped with react-native. It will be deprecated now that RN62 has been released I think. IMO the DX will be best if it shipped with react-native-web, and it's probably only a few lines of code to implement this on the web.

**Comment by necolas** [comment]
Maybe one of you can submit a PR for it

**Comment by SuhairZain** [comment]
@MoOx What did you mean by "Animated useNativeDriver is now required."? Are we required to pass that option every time we run an animation?

**Comment by MoOx** [comment]
@SuhairZain yes I think so

**Comment by xmxxd** [comment]
@necolas High I followed your work here after extensively searching the internet. can you write me here tyadsss@gmail.com?
I need your expertice. Thanks

**Comment by deggertsen** [comment]
Did isReduceMotionEnabled() ever get added? It shows that it's not checked off in the issue summary and we haven't been able to get it to work on web which led us here. Does anyone have additional info on that?
